extensions = {

    'Images':[
        '.png',
        '.jpeg',
        '.jpg',
        '.gif',
        '.ai',
        '.bmp',
        '.ico',
        '.ps',
        '.psd',
        '.svg',
        '.tif'
    ],

    'Sounds':[
        '.wav',
        '.mp3',
        '.m4a',
        '.mid',
        '.midi',
        '.ogg',
        '.wma',
        '.wpl',
        '.cda'
    ],

    'Videos':[
        '.mp4',
        '.mkv',
        '.avi',
        '.webm',
        '.3g2',
        '.3gp',
        '.flv',
        '.h264',
        '.m4v',
        '.mov',
        '.mpg',
        '.mpeg',
        '.wmv'
    ],
    'Documents':[
        '.pdf',
        '.docx',
        '.doc',
        '.pptx',
        '.pptm',
        '.ppt',
        '.txt',
        '.torrent',
        '.ods',
        '.odt',
        '.xls',
        '.xlsm',
        '.xlsx',
        '.rtf',
        '.wpd'
    ],
    'Android':[
        '.apk',
        '.xapk'
    ],
    'Compressed':[
        '.zip',
        '.rar',
        '.tar.xz',
        '.xz',
        '.7z',
        '.gz',
        '.arj',
        '.pkg',
        '.tar.gz',
        '.z',
        '.tar',
        '.tgz',
        '.bz2'
    ],
    'Executables':[
        '.exe',
        '.bat',
        '.bin',
        '.cgi',
        '.pl',
        '.jar',
        '.msi',
        '.wsf',
        '.deb'
    ],
    'Midia':[
        '.bin',
        '.dmg',
        '.iso',
        '.cso',
        '.toast',
        '.vcd'
    ],
    'Data':[
        '.csv',
        '.dat',
        '.db',
        '.dbf',
        '.log',
        '.mdb',
        '.sav',
        '.sql',
        '.xml'
    ],
    'Fonts':[
        '.fnt',
        '.fon',
        '.otf',
        '.ttf',
        '.woff2'
    ],
    'Programming':[
        '.htm',
        '.html',
        '.php',
        '.css',
        '.js',
        '.jsp',
        '.rss',
        '.xhtml',
        '.c',
        '.cs',
        '.h',
        '.java',
        '.sh',
        '.swift',
        '.vb',
        '.json',
        '.py'
    ],
    'System':[
        '.bak',
        '.cfg',
        '.dll',
        '.ini',
        '.lnk',
        '.sys',
        '.tmp'
    ]

}